### ISSUE TITLE
just syntax check breaks CI build

### ISSUE THREAD

**Issue by plata** [ublue-os/startingpoint#204]
The just syntax checker introduced in #194 breaks the CI build. The `--fmt` resolves the includes (see https://github.com/casey/just/issues/1585).

I do not understand why this doesn't happen in this repository but it fails for me in https://github.com/plata/ublue-surface/pull/48.

**Comment by xynydev** [comment]
Hmm. If formatting resolves the includes inline and consequently breaks the syntax check then we have a problem and should remove the just syntax checker for now. Can you confirm if this is the case? 

Besides, I now kind of feel like stripping extra features like this from build.yml would be preferable, since not every image will use just, and these could be supplied optionally as scripts or smth.

**Comment by plata** [comment]
> Can you confirm if this is the case?

This is what I see in the linked PR and issue and what happens when I run the command locally. So yes, I can confirm.

A workaround until the issue is fixed upstream could be to filter out files which contain `!include`.

**Comment by xynydev** [comment]
If the syntax check always fails when using includes, I guess the syntax check should be removez.

I don't think the workaround would be the thing to go for here. Do you wish to PR in the removal of the just check? Adding this back later as a separate action or a part of bling could be re-discussed later.
