### ISSUE TITLE
fix: Image build not pulling in recipe.yml

### ISSUE THREAD

**Issue by ayhc** [ublue-os/startingpoint#25]
Over the last day or so (after #23 was committed), I've encountered the following error when trying to build the image:

    -- Installing RPMs defined in recipe.yml --
    Error: read /dev/stdin: is a directory

The built image does not include any of the packages listed in recipe.yml.

**Comment by sbaue** [comment]
Issue is in containerfile line 1-3:

`ARG FEDORA_MAJOR_VERSION=37
ARG BASE_CONTAINER_URL=ghcr.io/ublue-os/silverblue-main
ARG RECIPE`

Recipe is undefined. Then later on in line 11 we do:

`COPY ${RECIPE} /tmp/ublue-recipe.yml`

Which fails to do anything because we don't actually copy any file in the step before that. Which in turn causes build errors in build.yml since that expects recipe.yml to be  in the root directory in line 32-34.

` matrix:
        recipe:
          - recipe.yml`

**Comment by EinoHR** [comment]
fixed in #26
