### ISSUE TITLE
refactor: clean up scripts functionality

### ISSUE THREAD

**Issue by EinoHR** [ublue-os/startingpoint#53]
* no need to define in recipe
* support both pre and post scripts
* `scripts/pre` & `scripts/post`

**Comment by Arcitec** [comment]
Oh wow... I actually didn't see any of these tickets before I made the big pull request, hehe.

> no need to define in recipe

I would say that there are some strong needs for having to define the script list in the recipe, for 3 reasons:

1. Multiple recipes can be defined, each running different scripts. **This is the hardest thing to solve if explicit script lists are removed.**
2. "Library" / "Helper" scripts can be included, which won't auto-run and will simply be included or executed by the *actual* scripts you *do* want to run. For example, you might have a helper script that interacts with some online service to fetch some data. By itself, it's useless. But you need to call it from your main script. Currently, this is easy; you just put both in the "scripts" folder and only call the "main" script from the recipe. If it's changed to auto-run all scripts, then there needs to be something like a `scripts/lib` folder that gets included without auto-running.
3. The recipe also ensures that scripts run in an exact, specific order. Although that can usually be solved with filename tricks (`10-run_me_early.sh` vs `99-run_me_last.sh`).

The idea of having pre/post scripts is great though. That could be added pretty easily, with a `.scripts.pre[]` and `.scripts.post[]` section in the yaml which simply is two separate lists of which scripts to run. And there wouldn't be any need to separate them into different folders. Just some yaml and build.sh changes.

**Comment by Arcitec** [comment]
I just had an idea...

The big issues that are created by auto-running scripts could be shoveled down into being the responsibility of *a script* instead.

Meaning: We (or someone else) can create a script that simply runs all other scripts. The user then simply has to include THAT script in their `recipe.yml` and they'll get the desired effect. Without having to break the great features I mentioned above.

I've finished implementing the pre/post script system and it's robust enough that I'll add it to the pull request. :)

**Comment by EinoHR** [comment]
I was planning on making this very simple, where everything is a "script" and they're ran in the exact order specified in the recipe. But this smells like bash scripting, and I trust anybody other than me to do that...

**Comment by Arcitec** [comment]
> where everything is a "script" and they're ran in the exact order specified in the recipe.

@EinoHR I'm not sure what you;'re referring to? The first bullet point of your original list was "no need to define in recipe" which I interpreted as "just automatically run every script in the folders". Which is a great idea, so that's what I implemented via the autorunner. :) But since an autorunner can conflict with the flexibility of building multiple different `recipe.yml` files with *different* script requirements in each, it was implemented as an included script module, `autorun.sh`.

This new setup gives people the best of both worlds. In the new default `recipe.yml`, the autorunner is enabled for both script stages, and people just need to dump scripts into `scripts/pre/*.sh` and `scripts/post/*.sh` and can relax and enjoy the magic. :)

But anyone who has more requirements than that can use the manual method, or both methods combined (via the techniques described in the inline code documentation of `autorun.sh`).

If there's any other ideas or use-cases I've missed, please let me know! :)

**Comment by EinoHR** [comment]
> I'm not sure what you're referring to?

Just something I was quietly planning, not something I wrote in the original issue (more of a reminded for myself, really). I'm just not a wizard enough to do what you did, so I had planned to implement a way simpler system, that could separate things from `build.sh`  like adding the flatpaks and installing rpms as scripts with a specific order set in the recipe.

**Comment by Arcitec** [comment]
@EinoHR Ahh okay, I understand. :) Well I am happy to contribute scripts with "two decades of heavy bash scripting knowledge". It can often feel useless to have this knowledge, since so many projects are written in modern languages and don't need much scripting, so it's nice that it finally comes to some use here for this build system! :heart:

**Comment by EinoHR** [comment]
> so many projects are written in modern languages

_I did fantasize about a version of this that feels like real programming the other day... Like parsing a `yml` file with a library, generating a Containerfile based on it, building it and doing all that signing and ghcr pushing stuff, all through a cli._

**Comment by Arcitec** [comment]
Haha yeah I had the same thought that it would be nice to have a "proper" build tool. Maybe someone will do it as a future project enhancement. But the current scripting is a nice solution anyway. It's robust, the error-checking is strict, and it's really easy to use now. Just a `recipe.yml` and the `scripts/*`-folders, for most people! :)
