### ISSUE TITLE
add the ability to add nix applications to recipe.yml

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/startingpoint#77]
There should be a variable like this. it can either be false or true. this variable configures if nix should be installed automatically or not.

```yml
nix: true
```

then

```yml
nixapps:
- nixpkgs#htop
- nixpkgs#btop
- nixpkgs#virt-manager
- nixpkgs#distrobox
- nixpkgs#toolbox
```

**Comment by EinoHR** [comment]
* Nix is not installed by default (flatpak is), and cannot be installed in the image AFAIK so the installation should be handled after first boot, and IMO that's something for the user to do rather than us
* We already had a debate about `just update` updating Nix applications and came to the conclusion that it's futile, since there's many different ways to install Nix stuff. 
* Yafti is not built to install Nix applications so this would have to be a custom screen.
* Fleek is closely related to uBlue (being a part of the org), and it uses home manager. If you want some Nix packages to be available ootb you could ship a `fleek.yml` or home manager config in your own image and instruct users (or yourself) to use that.

You can always add such a feature to your own image, though, but with the diversity of the Nix ecosystem I doubt such a feature should ever be added to this template. Even the Nix install script is kind of on shaky ground.

**Comment by dnkmmr69420** [comment]
I'm gonna do this myself
