### ISSUE TITLE
Image not pushed to ghcr since last commits

### ISSUE THREAD

**Issue by MiMillieuh** [ublue-os/startingpoint#82]
Hello, I've merged today 4 commits from the main starting point branch and it seem to not being uploading the image to ghcr.

It does the same with a new repo. 

Any clue on the issue ? 

![image](https://github.com/ublue-os/startingpoint/assets/52078885/8be1692c-56d7-4491-8a30-b5ebcb9d9758)

**Comment by MiMillieuh** [comment]
It can be fixed by reverting workflow in the .github folder.

https://github.com/ublue-os/startingpoint/pull/83

**Comment by xynydev** [comment]
@MiMillieuh We went through a branch restructuring making it so that all branches are built but only the branch called `live` is pushed to GHCR. The repo is still in a _sometimes there are breaking changes_ phase, but after 1.0 I'll try to keep that to a minimum. This change could have been communicated about more clearly, though it was followed by changes in the README and ublue.it docs.

I recommend you rename the default branch of your custom repo to `live` and go back to the latest changes.
